name: window_manager
description: This plugin allows Flutter desktop apps to resizing and repositioning the window.
version: 0.2.6
homepage: https://github.com/leanflutter/window_manager

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.2.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  screen_retriever: ^0.2.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowManagerPlugin
      macos:
        pluginClass: WindowManagerPlugin
      windows:
        pluginClass: WindowManagerPlugin
  assets:
    - images/ic_chrome_close.png
    - images/ic_chrome_maximize.png
    - images/ic_chrome_minimize.png
    - images/ic_chrome_unmaximize.png
